### ISSUE TITLE
Only notify if certain category

### ISSUE THREAD

**Issue by camjac251** [LVH-IT/TwitchCategoryChangeDetector#1]
Would it be possible to whitelist certain categories? I was hoping to watch for when a streamer switches to the Watch Parties category https://www.twitch.tv/directory/game/Watch%20Parties

**Comment by LVH-IT** [comment]
Currently not possible, but I'll look into adding it as well as your other request (#2).

**Comment by LVH-IT** [comment]
Added in [v0.3.0-beta](https://github.com/LVH-IT/TwitchCategoryChangeDetector/releases/tag/v0.3.0-beta). I haven't yet thoroughly tested this feature though.
